### ISSUE TITLE
Doing it Wrong: WP_User_Query:query was called incorrectly 

### ISSUE THREAD

**Issue by sangeetha-nayak** [newfold-labs/wp-module-install-checker#2]
**Summarize the issue (briefly)**
Function WP_User_Query::query was called incorrectly. User queries should not be run before the plugins_loaded hook PHP notice is shown for following usage.
1. wp-content/plugins/dist/vendor/newfold-labs/wp-module-install-checker/includes/InstallChecker.php:60
NewfoldLabs\W\M\I\InstallChecker->isFreshInstallation()
2. wp-content/plugins/dist/vendor/newfold-labs/wp-module-install-checker/includes/InstallChecker.php:29
{closure}()
3. wp-content/plugins/dist/vendor/newfold-labs/wp-module-install-checker/bootstrap.php:33
NewfoldLabs\Container\Container->get()

**Steps to reproduce**
  1. On latest plugin dashboard, via Query Monitor

**Screenshots**
![Screenshot (524)](https://github.com/newfold-labs/wp-module-install-checker/assets/138747461/89408f48-c45f-4454-8300-a20fd972e544)
![Screenshot (525)](https://github.com/newfold-labs/wp-module-install-checker/assets/138747461/af528363-b1cc-42aa-b0d2-e7c7aa619b2c)

**Bluehost Plugin Version:**
* Version: Latest 3.9.4

**Browser (with version) & Operating System (with version)**
  * Browser: Chrome
  * Operating System: Win 10
  * Device: WIndows

**Comment by wpscholar** [comment]
Closing as https://github.com/newfold-labs/wp-module-activation/pull/7/ should solve the issue.
